-- AlterTable
ALTER TABLE `project` ADD COLUMN `budget` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `done_budget` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `progress` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `tax` DOUBLE NOT NULL DEFAULT 0.15,
    ADD COLUMN `total_budget` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `sub_task` ADD COLUMN `budget` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `done_budget` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `task_manager` ADD COLUMN `budget` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `done_budget` DOUBLE NOT NULL DEFAULT 0;
